Update to examples from _bash Cookbook Second Edition_

diff --git a/ch16/func_tweak_path b/ch16/func_tweak_path
--- a/ch16/func_tweak_path
+++ b/ch16/func_tweak_path
@@ -20,7 +20,7 @@ function add_to_path {
     if [ $(echo $directory | grep '^/') ]; then
         :echo "$0:$FUNCNAME: '$directory' is absolute" >&2
     else
-        echo "$0:$FUNCNAME: can't add relative directory '$directory' to the \$PATH" >&2
+        echo "$0:$FUNCNAME: can't add relative directory '$directory' to \$PATH" >&2
         return 1
     fi
 
@@ -32,7 +32,7 @@ function add_to_path {
         return 1
     fi
 
-    # Make sure it's not already in the PATH
+    # Make sure it's not already in the $PATH
     if [ $(contains "$PATH" "$directory") ]; then
         echo "$0:$FUNCNAME: '$directory' already in \$PATH--aborting" >&2
     else
@@ -70,7 +70,7 @@ function rm_from_path {
 
 #+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 # Remove leading/trailing or duplicate ':', remove duplicate entries
-# Returns: echos the "cleaned up" path
+# Returns: echoes the "cleaned up" path
 # Called like: cleaned_path=$(clean_path $PATH)
 function clean_path {
     local path=$1
diff --git a/settings/bashrc b/settings/bashrc
--- a/settings/bashrc
+++ b/settings/bashrc
@@ -1,15 +1,17 @@
 # cookbook filename: bashrc
 
 # settings/bash_profile: subshell environment settings
-# To re-read (and implement changes to this file) use:
+# To reread (and implement changes to this file) use:
 # source $SETTINGS/bashrc
 
-# Fail-safe. This should be set when we're called, but if not, the
+# Only if interactive bash with a terminal!
+[ -t 1 -a -n "$BASH_VERSION" ] || return
+
+# Failsafe.  This should be set when we're called, but if not, the
 # "not found" error messages should be pretty clear.
 # Use leading ':' to prevent this from being run as a program after
 # it is expanded.
 : ${SETTINGS:='SETTINGS_variable_not_set'}
-
 
 # DEBUGGING only--will break scp, rsync
 # echo "Sourcing $SETTINGS/bash_profile..."
@@ -17,38 +19,51 @@
 # set -x
 
 # Debugging/logging--will not break scp, rsync
-#case "$-" in
+# case "$-" in
 #    *i*) echo "$(date '+%Y-%m-%d_%H:%M:%S_%Z') Interactive" \
 #              "$SETTINGS/bashrc ssh=$SSH_CONNECTION" >> ~/rc.log ;;
-#    *  ) echo "$(date '+%Y-%m-%d_%H:%M:%S_%Z') Non-interactive" \
+#    *  ) echo "$(date '+%Y-%m-%d_%H:%M:%S_%Z') Noninteractive" \
 #              "$SETTINGS/bashrc ssh=$SSH_CONNECTION" >> ~/rc.log ;;
 #esac
 
-
-# In theory this is also sourced from /etc/bashrc (/etc/bash.bashrc )
-# or ~/.bashrc to apply all these settings to login shells too. In practice
+# In theory this is also sourced from /etc/bashrc (/etc/bash.bashrc)
+# or ~/.bashrc to apply all these settings to login shells too.  In practice
 # if these settings only work sometimes (like in subshells), verify that.
 
+# Source keychain file (if it exists) for SSH and GPG agents
+[ -r "$HOME/.keychain/${HOSTNAME}-sh" ] \
+  && source "$HOME/.keychain/${HOSTNAME}-sh"
+[ -r "$HOME/.keychain/${HOSTNAME}-sh-gpg" ] \
+  && source "$HOME/.keychain/${HOSTNAME}-sh-gpg"
 
 # Set some more useful prompts
-# Interactive command line prompt.
+# Interactive command-line prompt
 # ONLY set one of these if we really are interactive, since lots of people
-# (even use sometimes) test to see if a shell is interactive using
-# something like: if [ "$PS1" ]; then
+# (even us sometimes) test to see if a shell is interactive using
+# something like:  if [ "$PS1" ]; then
 case "$-" in
     *i*)
         #export PS1='\n[\u@\h t:\l l:$SHLVL h:\! j:\j v:\V]\n$PWD\$ '
         #export PS1='\n[\u@\h:T\l:L$SHLVL:C\!:\D{%Y-%m-%d_%H:%M:%S_%Z}]\n$PWD\$ '
         export PS1='\n[\u@\h:T\l:L$SHLVL:C\!:J\j:\D{%Y-%m-%d_%H:%M:%S_%Z}]\n$PWD\$ '
-        #export PS2='> '                      # Secondary (i.e. continued) prompt
-        #export PS3='Please make a choice: '  # Select prompt
-        export PS4='+xtrace $LINENO: '        # xtrace (debug) prompt
+        #export PS2='> ' # Secondary (i.e. continued) prompt
+
+        #export PS3='Please make a choice: '          # Select prompt
+        #export PS4='+xtrace $LINENO: '                # xtrace (debug) prompt
+        export PS4='+xtrace $BASH_SOURCE::$FUNCNAME-$LINENO: ' # xtrace prompt
+
+        # If this is an xterm set the title to user@host:dir
+        case "$TERM" in
+            xterm*|rxvt*) 
+                PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}:$PWD\007"'
+            ;;
+        esac
     ;;
 esac
 
-# Make sure custom inputrc is handled, if we can find it, note different
+# Make sure custom inputrc is handled, if we can find it; note different
 # names. Also note different order, since for this one we probably want
-# our custom settings to over-ride the system file, if present.
+# our custom settings to override the system file, if present.
 for file in $SETTINGS/inputrc ~/.inputrc /etc/inputrc; do
     [ -r "$file" ] && export INPUTRC="$file" && break # Use first found
 done
@@ -57,37 +72,45 @@ done
 # See also /etc/security/limits.conf on many Linux systems.
 ulimit -S -c 0 > /dev/null 2>&1
 
-# Don't let CTRL-D exit the shell
-set -o ignoreeof
-
 # Set various aspects of the bash history
 export HISTSIZE=5000          # Num. of commands in history stack in memory
-export HISTFILESIZE=5000      # Num. of commands in history FILE
-export HISTCONTROL=ignoreboth # bash < 3, omit dups & lines starting with space
-export HISTIGNORE='&:[ ]*'    # bash >= 3, omit dups & lines starting with space
-#export HISTTIMEFORMAT='%Y-%m-%d_%H:%M:%S_%Z=' # bash >= 3, time-stamp hist file
+export HISTFILESIZE=5000      # Num. of commands in history file
+#export HISTCONTROL=ignoreboth # bash < 3, omit dups & lines starting with spaces
+export HISTCONTROL='erasedups:ignoredups:ignorespace'
+export HISTIGNORE='&:[ ]*'    # bash >= 3, omit dups & lines starting with spaces
+#export HISTTIMEFORMAT='%Y-%m-%d_%H:%M:%S_%Z=' # bash >= 3, timestamp hist file
 shopt -s histappend           # Append rather than overwrite history on exit
 shopt -q -s cdspell           # Auto-fix minor typos in interactive use of 'cd'
 shopt -q -s checkwinsize      # Update the values of LINES and COLUMNS
-shopt -q -s cmdhist           # Make multi-line commands 1 line in history
-set -o notify   # (or set -b) # Immediate notification of bckgrnd job termintn.
+shopt -q -s cmdhist           # Make multiline commands 1 line in history
+set -o notify   # (or set -b) # Immediate notif. of background job termination.
+set -o ignoreeof              # Don't let Ctrl-D exit the shell
 
 # Other bash settings
+PATH="$PATH:/opt/bin"
+export MANWIDTH=80          # Manpage width, use < 80 if COLUMNS=80 & less -N
 export LC_COLLATE='C'         # Set traditional C sort order (e.g. UC first)
-export HOSTFILE='/etc/hosts'  # Use /etc/hosts for host name completion
-export CDPATH='~/:.:..:../..' # Similar to $PATH, but for use by 'cd'
+export HOSTFILE='/etc/hosts'  # Use /etc/hosts for hostname completion
+export CDPATH='.:~/:..:../..' # Similar to $PATH, but for use by 'cd'
 # Note that the '.' in $CDPATH is needed so that cd will work under POSIX mode
 # but this will also cause cd to echo the new directory to STDOUT!
+# And see also "cdspell" above!
 
-# Import bash completion settings, if they exist in the default location.
+# Import bash completion settings, if they exist in the default location
+# and if not already imported (e.g. "$BASH_COMPLETION_COMPAT_DIR" NOT set).
 # This can take a second or two on a slow system, so you may not always
 # want to do it, even if it does exist (which it doesn't by default on many
 # systems, e.g. Red Hat).
-# [ -r /etc/bash_completion ] && source /etc/bash_completion
+if [ -z "$BASH_COMPLETION_COMPAT_DIR" ] && ! shopt -oq posix; then
+    if [ -f /usr/share/bash-completion/bash_completion ]; then
+      . /usr/share/bash-completion/bash_completion
+    elif [ -f /etc/bash_completion ]; then
+      . /etc/bash_completion
+    fi
+fi
 
-
-# Use a lesspipe filter, if we can find it. This sets the $LESSOPEN variable
-# Globally replace the $PATH ':' delimiter with space for use in a list
+# Use a lesspipe filter, if we can find it.  This sets the $LESSOPEN variable.
+# Globally replace the $PATH ':' delimiter with space for use in a list.
 for path in $SETTINGS /opt/bin ~/ ${PATH//:/ }; do
     # Use first one found of 'lesspipe.sh' (preferred) or 'lesspipe' (Debian)
     [ -x "$path/lesspipe.sh" ] && eval $("$path/lesspipe.sh") && break
@@ -95,16 +118,16 @@ for path in $SETTINGS /opt/bin ~/ ${PATH//:/ }; do
 done
 
 # Set other less & editor prefs (overkill)
-export LESS="--LONG-PROMPT --LINE-NUMBERS --QUIET"
-export VISUAL='vi' # Set a default that should always work
+export LESS="--LONG-PROMPT --LINE-NUMBERS --ignore-case --QUIET --no-init"
+export VISUAL='vi'  # Set a default that should always work
 # We'd rather use 'type -P' here, but that was added in bash-2.05b and we use
-# systems we don't control with versions older than that. We can't easily
+# systems we don't control with versions older than that.  We can't easily
 # use 'which' since that produces output whether the file is found or not.
-for path in ${PATH//:/ }; do
-    # Overwrite VISUAL if we can find nano
-    [ -x "$path/nano" ] \
-      && export VISUAL='nano --smooth --const --nowrap --suspend' && break
-done
+#for path in ${PATH//:/ }; do
+#    # Overwrite VISUAL if we can find nano
+#    [ -x "$path/nano" ] \
+#      && export VISUAL='nano --smooth --const --nowrap --suspend' && break
+#done
 # See above notes re: nano for why we're using this for loop
 for path in ${PATH//:/ }; do
     # Alias vi to vim in binary mode if we can
@@ -114,74 +137,131 @@ export EDITOR="$VISUAL"      # Yet Another Possibility
 export SVN_EDITOR="$VISUAL"  # Subversion
 alias edit=$VISUAL           # Provide a command to use on all systems
 
-# Set ls options and aliases
+# Set ls options and aliases.
 # Note all the colorizing may or may not work depending on your terminal
 # emulation and settings, esp. ANSI color. But it shouldn't hurt to have.
-# See above notes re: nano for why we're using this for loop
+# See above notes re: nano for why we're using this for loop.
 for path in ${PATH//:/ }; do
     [ -r "$path/dircolors" ] && eval "$(dircolors)" \
       && LS_OPTIONS='--color=auto' && break
 done
 export LS_OPTIONS="$LS_OPTIONS -F -h"
 # Using dircolors may cause csh scripts to fail with an
-# "Unknown colorls variable `do'." error. The culprit is the ":do=01;35:"
-# part in the LS_COLORS environment variable. For a possible solution see
+# "Unknown colorls variable 'do'." error.  The culprit is the ":do=01;35:"
+# part in the LS_COLORS environment variable.  For a possible solution see
 # http://forums.macosxhints.com/showthread.php?t=7287
 # eval "$(dircolors)"
 alias ls="ls $LS_OPTIONS"
 alias ll="ls $LS_OPTIONS -l"
-alias ll.="ls $LS_OPTIONS -ld" # Usage: ll. ~/.*
+alias ll.="ls $LS_OPTIONS -ld"  # Usage: ll. ~/.*
 alias la="ls $LS_OPTIONS -la"
+alias lrt="ls $LS_OPTIONS -alrt"
 
 # Useful aliases
-alias bot='cd $(dirname $(find . | tail -n 1))'
+# Moved to a function: alias bot='cd $(dirname $(find . | tail -1))'
+#alias clip='xsel -b'         # pipe stuff into right "X" clipboard
+alias gc='xsel -b'           # "GetClip" get stuff from right "X" clipboard
+alias pc='xsel -bi'          # "PutClip" put stuff to right "X" clipboard
 alias clr='cd ~/ && clear'   # Clear and return $HOME
 alias cls='clear'            # DOS-ish for clear
+alias cal='cal -M'           # Start calendars on Monday
 alias copy='cp'              # DOS-ish for cp
 #alias cp='cp -i'            # Annoying Red Hat default from /root/.bashrc
 alias cvsst='cvs -qn update' # Hack to get concise CVS status (like svn st)
 alias del='rm'               # DOS-ish for rm
-alias diff='\diff -u'        # Make unified diffs the default
-alias jdiff="\diff --side-by-side --ignore-case --ignore-blank-lines \
+alias df='df --print-type --exclude-type=tmpfs --exclude-type=devtmpfs'
+alias diff='diff -u'         # Make unified diffs the default
+alias jdiff="\diff --side-by-side --ignore-case --ignore-blank-lines\
   --ignore-all-space --suppress-common-lines" # Useful GNU diff command
 alias dir='ls'               # DOS-ish for ls
-alias hr='history -a && history -n' # Append current, then re-read history
+alias hu='history -n && history -a' # Read new hist. lines; append current lines
+alias hr='hu'                # "History update" backward compat to 'hr'
+alias inxi='inxi -c19'       # (Ubuntu) system information script
 alias ipconfig='ifconfig'    # Windows-ish for ifconfig
+alias lesss='less -S'        # Don't wrap lines
+alias locate='locate -i'     # Case-insensitive locate
+alias man='LANG=C man'       # Display manpages properly
 alias md='mkdir'             # DOS-ish for mkdir
 alias move='mv'              # DOS-ish for mv
-#alias mv='mv -i'             # Annoying Red Hat default from /root/.bashrc
+#alias mv='mv -i'            # Annoying Red Hat default from /root/.bashrc
 alias ntsysv='rcconf'        # Debian rcconf is pretty close to Red Hat ntsysv
+#alias open='gnome-open'     # Open files & URLs using GNOME handlers; see run below
 alias pathping='mtr'         # mtr - a network diagnostic tool
+alias ping='ping -c4'        # Only 4 pings by default
 alias r='fc -s'              # Recall and execute 'command' starting with...
 alias rd='rmdir'             # DOS-ish for rmdir
+# Tweaked from http://bit.ly/2fc4e8Z
+alias randomwords="shuf -n102 /usr/share/dict/words \
+  | perl -ne 'print qq(\u\$_);' | column"
 alias ren='mv'               # DOS-ish for mv/rename
 #alias rm='rm -i'            # Annoying Red Hat default from /root/.bashrc
-alias svnpropfix='svn propset svn:keywords "Id URL"'
+alias reloadbind='rndc -k /etc/bind/rndc.key freeze \
+  && rndc -k /etc/bind/rndc.key reload && rndc -k /etc/bind/rndc.key thaw'
+  # Reload dynamic BIND zones after editing db.* files
+alias svndiff='meld'         # Cool GUI diff, similar to TortoiseMerge
+alias svnpropfix='svn propset svn:keywords "id url date"'
+alias svnkey='svn propset svn:keywords "id url"'
+alias svneol='svn propset svn:eol-style'  # One of 'native', 'LF', 'CR', 'CRLF'
+alias svnexe='svn propset svn:executable on'
+alias top10='sort | uniq -c | sort -rn | head'
 alias tracert='traceroute'   # DOS-ish for traceroute
 alias vzip='unzip -lvM'      # View contents of ZIP file
 alias wgetdir="wget --no-verbose --recursive --no-parent --no-directories \
-  --level=1"                 # Grab a whole directory using wget
+ --level=1"                  # Grab a whole directory using wget
+alias wgetsdir="wget --no-verbose --recursive --timestamping --no-parent \
+ --no-host-directories --reject 'index.*'"  # Grab a dir and subdirs
 alias zonex='host -l'        # Extract (dump) DNS zone
 
-# if the script exists and is executable, create an alias to get
+# Date/time
+alias iso8601="date '+%Y-%m-%dT%H:%M:%S%z'"  # ISO 8601 time
+alias now="date       '+%F %T %Z(%z)'"       # More readable ISO 8601 local
+alias utc="date --utc '+%F %T %Z(%z)'"       # More readable ISO 8601 UTC
+
+# Neat stuff from http://xmodulo.com/useful-bash-aliases-functions.html
+alias meminfo='free -m -l -t'   # See how much memory you have left
+alias whatpid='ps auwx | grep'  # Get PID and process info
+alias port='netstat -tulanp'    # Show which apps are connecting to the network
+
+# If the script exists and is executable, create an alias to get
 # web server headers
 for path in ${PATH//:/ }; do
     [ -x "$path/lwp-request" ] && alias httpdinfo='lwp-request -eUd' && break
 done
 
-# Try to use kbdrate to make the keyboard go faster, but don't complain if
-# it's not there. Easier/faster to throw out error if it's not there...
-kbdrate -r 30.0 -d 250 &> /dev/null
-
 
 # Useful functions
+
+# Use 'gnome-open' to "run" things
+function run {
+    [ -r "$*" ] && {
+        gnome-open "$*" >& /dev/null
+    } || {
+        echo "'$*' not found or not readable!"
+    }
+}
+
+
+# Python version of 'perl -c'
+function python-c {
+    python -m py_compile "$1" && rm -f "${1}c"
+}
+
+
+# cd to the bottom of a narrow but deep dir tree
+function bot {
+    local dir=${1:-.}
+    #\cd $(dirname $(find $dir | tail -1))
+    \cd $(find . -name CVS -prune -o -type d -print | tail -1)
+}
+
 
 # mkdir newdir then cd into it
 # usage: mcd (<mode>) <dir>
 function mcd {
     local newdir='_mcd_command_failed_'
     if [ -d "$1" ]; then         # Dir exists, mention that...
-        echo $1 exists...
+        echo "$1 exists..."
+        newdir="$1"
     else
         if [ -n "$2" ]; then     # We've specified a mode
             command mkdir -p -m $1 "$2" && newdir="$2"
@@ -193,12 +273,16 @@ function mcd {
 } # end of mcd
 
 
-# Trivial command line calculator
+# Trivial command-line calculator
 function calc {
     # INTEGER ONLY! --> echo The answer is: $(( $* ))
     # Floating point
-    awk "BEGIN {print \"The answer is: \" $* }";
+    awk "BEGIN {print \"$* = \" $* }";
+    #awk "BEGIN {printf \"$* = %f\", $* }";
 } # end of calc
+function addup {
+    awk '{sum += $1} END {print sum}'
+}
 
 
 # Allow use of 'cd ...' to cd up 2 levels, 'cd ....' up 3, etc. (like 4NT/4DOS)
@@ -207,16 +291,16 @@ function cd {
 
     local option= length= count= cdpath= i= # Local scope and start clean
 
-    # If we have a -L or -P sym link option, save then remove it
+    # If we have a -L or -P symlink option, save then remove it
     if [ "$1" = "-P" -o "$1" = "-L" ]; then
         option="$1"
         shift
     fi
 
-    # Are we using the special syntax? Make sure $1 isn't empty, then
-    # match the first 3 characters of $1 to see if they are '...' then
+    # Are we using the special syntax?  Make sure $1 isn't empty, then
+    # match the first 3 characters of $1 to see if they are '...', then
     # make sure there isn't a slash by trying a substitution; if it fails,
-    # there's no slash. Both of these string routines require Bash 2.0+
+    # there's no slash.
     if [ -n "$1" -a "${1:0:3}" = '...' -a "$1" = "${1%/*}" ]; then
         # We are using special syntax
         length=${#1}  # Assume that $1 has nothing but dots and count them
@@ -239,7 +323,7 @@ function cd {
 } # end of cd
 
 
-# Do site or host specific things here
+# Do site- or host-specific things here
 case $HOSTNAME in
     *.company.com     ) # source $SETTINGS/company.com
                       ;;
